# Online Dataset
url_dataset: 'https://www.dropbox.com/s/24s1jjgn5bjhb8g/audios-20190517T000334Z-001.zip?dl=1'
compressed_data_name: 'audios-20190517T000334Z-001.zip'

# Directories for dataset and checkpoints
data_dir: 'dataset'
data_dir_audios: 'audios'
data_dir_fragments: 'audio_fragments'
data_dir_images: 'images'
label_id_json: 'labels.json'
model_dir: 'checkpoints'

# Data files
test_data: 'test.txt'
training_data: 'training.txt'
validation_data: 'validation.txt'

# Data configuration
image_shape: [110,480]

# Params that affect preprocessing
save_audio_fragments: False
window_length: 35280
shift_frames: 22050
frames: 3
num_classes: 10

# Parameters that may affect training
batch_size: 8
class_mode: 'other'
num_epochs: 10
learning_rate: 0.001
loss: 'sparse_categorical_crossentropy'
shuffle: True