# Online Dataset
url_dataset: 'https://www.dropbox.com/s/ycv53b3c9xe32fs/audios-20190928T015626Z-001.rar?dl=1'
compressed_data_name: 'audios-20190928T015626Z-001.rar'

# Directories for dataset and checkpoints
data_dir: 'dataset'
data_dir_audios: 'audios'
data_dir_fragments: 'audio_fragments'
data_dir_images: 'images'
label_id_json: 'labels.json'
model_dir: 'checkpoints'

# Data files
test_data: 'test.txt'
training_data: 'training.txt'
validation_data: 'validation.txt'

# Data configuration
image_shape: [110,480]

# Params that affect preprocessing
save_audio_fragments: True
window_length: 35280
shift_frames: 22050
frames: 3
num_classes: 10

# Parameters that may affect training
batch_size: 16
class_mode: 'other'
num_epochs: 30
learning_rate: 0.01
loss: 'sparse_categorical_crossentropy'
shuffle: True