# Online Dataset
url_dataset: 'https://www.dropbox.com/s/bq4iun13ug53x9c/audios-20190411T001746Z-001.zip?dl=1'
compressed_data_name: 'audios-20190411T001746Z-001.zip'

# Directories for dataset and checkpoints
data_dir: 'dataset'
data_dir_audios: 'audios'
data_dir_fragments: 'audio_fragments'
data_dir_images: 'images'
label_id_json: 'labels.json'
model_dir: 'checkpoints'

# Data files
test_data: 'test.txt'
training_data: 'training.txt'
validation_data: 'validation.txt'

# Data configuration
image_shape: [224,224]

# Params that affect preprocessing
save_audio_fragments: True
window_length: 35280
shift_frames: 22050
frames: 3
num_classes: 10

# Parameters that may affect training
batch_size: 5
class_mode: 'other'